-- Set3: Q1: Find how much amount spent by each customer on best artist? Write a query to return
-- customer name, artist name and total spent
WITH
	BEST_ARTISTS AS (
		SELECT
			ARTIST.ARTIST_ID AS ARTIST_ID,
			ARTIST.NAME AS ARTIST_NAME,
			SUM(INVOICE_LINE.UNIT_PRICE * INVOICE_LINE.QUANTITY) AS AMOUNT_SPENT
		FROM
			INVOICE_LINE
			JOIN TRACK ON TRACK.TRACK_ID = INVOICE_LINE.TRACK_ID
			JOIN ALBUM ON ALBUM.ALBUM_ID = TRACK.ALBUM_ID
			JOIN ARTIST ON ARTIST.ARTIST_ID = ALBUM.ARTIST_ID
		GROUP BY 1
		ORDER BY 3 DESC
		LIMIT 1
	)
SELECT
	C.CUSTOMER_ID,
	C.FIRST_NAME,
	C.LAST_NAME,
	ARR.ARTIST_NAME,
	SUM(IL.UNIT_PRICE * IL.QUANTITY) AS AMOUNT_SPENT_ON_ARTIST
FROM
	CUSTOMER C
	JOIN INVOICE INV ON INV.CUSTOMER_ID = C.CUSTOMER_ID
	JOIN INVOICE_LINE IL ON IL.INVOICE_ID = INV.INVOICE_ID
	JOIN TRACK ON TRACK.TRACK_ID = IL.TRACK_ID
	JOIN ALBUM ON ALBUM.ALBUM_ID = TRACK.ALBUM_ID
	JOIN ARTIST ON ARTIST.ARTIST_ID = ALBUM.ARTIST_ID
	JOIN BEST_ARTISTS ARR ON ARR.ARTIST_ID = ARTIST.ARTIST_ID
GROUP BY 1,2,3,4
ORDER BY 5 DESC


-- Set3: Q2: We want to find out the most popular music Genre for each country. We determine the
-- most popular genre as the genre with the highest amount of purchases. Write a query
-- that returns each country along with the top Genre. For countries where the maximum
-- number of purchases is shared return all Genres

WITH
	POPULAR_GENRE AS (
		SELECT
			COUNT(INVOICE_LINE.QUANTITY) AS PURCHASES,
			CUSTOMER.COUNTRY,
			GENRE.NAME,
			GENRE.GENRE_ID,
			ROW_NUMBER() OVER (
				PARTITION BY
					CUSTOMER.COUNTRY
				ORDER BY
					COUNT(INVOICE_LINE.QUANTITY) DESC
			) AS ROWNO
		FROM
			INVOICE_LINE
			JOIN INVOICE ON INVOICE.INVOICE_ID = INVOICE_LINE.INVOICE_ID
			JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
			JOIN TRACK ON TRACK.TRACK_ID = INVOICE_LINE.TRACK_ID
			JOIN GENRE ON GENRE.GENRE_ID = TRACK.GENRE_ID
		GROUP BY 2,3, 4
		ORDER BY 2 ASC, 1 DESC
	)
SELECT
	*
FROM
	POPULAR_GENRE
WHERE
	ROWNO <= 1


-- Set3: Q3: Write a query that determines the customer that has spent the most on music for each
-- country. Write a query that returns the country along with the top customer and how
-- much they spent. For countries where the top amount spent is shared, provide all
-- customers who spent this amount
WITH RECURSIVE
	CUSTOMER_WITH_COUNTRY AS (
		SELECT
			CUSTOMER.CUSTOMER_ID,
			FIRST_NAME,
			LAST_NAME,
			BILLING_COUNTRY,
			SUM(TOTAL) AS TOTAL_SPENDING
		FROM
			INVOICE
			JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
		GROUP BY 1, 2, 3, 4
		ORDER BY 1, 5 DESC
	),
	CUSTOMER_MAX_SPENDING AS (
		SELECT
			BILLING_COUNTRY,
			MAX(TOTAL_SPENDING) AS MAX_SPENDING
		FROM
			CUSTOMER_WITH_COUNTRY
		GROUP BY
			BILLING_COUNTRY
	)
SELECT
	CC.BILLING_COUNTRY,
	CC.FIRST_NAME,
	CC.LAST_NAME,
	CC.CUSTOMER_ID
FROM
	CUSTOMER_WITH_COUNTRY CC
	JOIN CUSTOMER_MAX_SPENDING MS ON CC.BILLING_COUNTRY = MS.BILLING_COUNTRY
WHERE
	CC.TOTAL_SPENDING = MS.MAX_SPENDING
ORDER BY 1;